@pathUrl = http://localhost:8080/apiv3
# @pathUrl = https://apiv3.area54sa.com.ar:8125/apiv3

#@credenciales = Basic A54APIDev A54API4470Dev!
#@credenciales = Basic A54APIProd A54API4470Prod!
@credenciales = Basic A54APIProdUniversal A54API4470ProdUniversal!

### Obtener los Ingresos de una Empresa
GET {{pathUrl}}/almacenaje/getIn/164/2021-06-01/2021-06-02
Authorization: {{credenciales}}

### Obtener los Egresos de una Empresa
GET {{pathUrl}}/almacenaje/getOut/164/2021-06-01/2021-06-02
Authorization: {{credenciales}}

### Obtener el almacenaje
GET {{pathUrl}}/almacenaje/getAlmacenado/164/2021-06-01/2021-06-02
Authorization: {{credenciales}}