// Exportar todos los íconos desde un solo lugar
export { default as StockIcon } from './StockIcon.vue'
export { default as OrdenesIcon } from './OrdenesIcon.vue'
export { default as GuiasIcon } from './GuiasIcon.vue'
export { default as InformesIcon } from './InformesIcon.vue'
export { default as EmpresasIcon } from './EmpresasIcon.vue'
export { default as SecurityIcon } from './SecurityIcon.vue'
export { default as TransporteIcon } from './TransporteIcon.vue'
export { default as SeguimientosIcon } from './SeguimientosIcon.vue'
export { default as BarcodeIcon } from './BarcodeIcon.vue'
export { default as AtrasIcon } from './AtrasIcon.vue'
export { default as ExcelIcon } from './ExcelIcon.vue'
export { default as PerfilIcon } from './PerfilIcon.vue'
export { default as LogoutIcon } from './LogoutIcon.vue'
export { default as ComprometidoIcon } from './ComprometidoIcon.vue'
